
###Manoj
name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
      uses: actions/checkout@V4
 #       run: 
 #         echo "cloning repo"
 #         echo "${{toJson(github)}}"
 #         git clone https://github.com/${{github.repository}}.git
